#!/bin/bash -x

hostname
date

export OUTDIR=$PBS_O_WORKDIR/job_output
export PATH=$PATH:$PBS_O_WORKDIR
export PATH=/usr/local/bin:/usr/local/sbin:/opt/moab/bin:/hpf/largeprojects/struglis/naim/miniconda3/envs/rbioenv2/bin:/hpf/largeprojects/struglis/naim/miniconda3/condabin:/usr/local/bin:/usr/local/sbin:/usr/lib64/qt-3.3/bin:/opt/moab/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/naim/bin:/hpf/largeprojects/struglis/naim/bin:$PATH

echo "Working dir is ${PBS_O_WORKDIR}"
cd $PBS_O_WORKDIR

echo "infile: $infile"
echo "outfile: $outfile"
Rscript code/run_logistic.R $infile $outfile

echo "Done"
